### ISSUE TITLE
suitecrm

### ISSUE THREAD

**Issue by ghost** [btactic/zsuitecrm#1]
Hello!

Are you going to support suitecrm ? Its a fork from sugarcrm beacuse they wont develop ther opensource edition anymore (https://suitecrm.com/)

**Comment by klemenag** [comment]
Hi,

is there any news regarding suitecrm / zsugra zimbra connector?

Does/should the current version of the connector work or it doesn't?

Kind regards

**Comment by adriangibanelbtactic** [comment]
zsugar supports suitecrm, yes.
