### ISSUE TITLE
Email attachments not working correctly, when saving email to SuiteCRM 7.x

### ISSUE THREAD

**Issue by gody01** [btactic/zsuitecrm#2]
Hello,

It seems that in redirect.jsp code after:
```
// Special Treatment for set_note_attachment REST method
        if ( method.equals("set_note_attachment")){
```    
is not working correctly.

Instead file content, it sends local URL to SuiteCRM api.

Relevant changes were introduced in:
git diff 399e7ea0770de3b587b27e858603fab431b0b4d1 8613076be3afb9d54b3d98c868490bec12e912c0

It seems, that code inside that if would not be executed:
```
        // Special Treatment for set_note_attachment REST method
        if ( method.equals("set_note_attachment")){
```

Captured Request To SuiteCRM:

```
input_type=JSON&method=set_note_attachment&response_type=JSON&rest_data=["vupvifgvmfrlgj0h17p2685bg5",{"id":"4263113f-c64b-1a69-0607-61ef1cdcaf4d","filename":"RVTools.pdf","file":"https://zimbra.agenda.si/service/home/~/RVTools.pdf?id=3716987&part=2","related_module_id":"11784a5a-71ff-bfdb-ce57-61ef1c8ff57c","related_module_name":"Emails"}]
```

while this:
`https://zimbra.agenda.si/service/home/~/RVTools.pdf?id=3716987&part=2`

should be base64 encoded content of this file.

**Comment by adriangibanelbtactic** [comment]
I think the problem might rely on not using streams while trying to adapt the code to ZCS 8.8.15.

This is one example but there are more.

```
ByteUtil.copy(get.getResponseBodyAsStream(), false, readFileStream, false);
ByteUtil.copy(httpResponse.getEntity().getContent(), false, readFileStream, false);
```

.

Not sure when I will be able to dig into this problem.

**Comment by adriangibanelbtactic** [comment]
Current master head fixes this problem.

If you want to test this, go ahead, download the source code, build your zip (as per the instructions) and test it.

I'll release a proper version in the next days and I'll close this issue.

**Comment by adriangibanelbtactic** [comment]
zSuitecrm v.1.6.0 has just been released and it will work as expected.

I close this issue.
